CREATE TABLE PERSON3244 (
DRIVER_ID VARCHAR(30),
NAME VARCHAR(50),
ADDRESS VARCHAR(100),
PRIMARY KEY(DRIVER_ID)
);

commit;

CREATE TABLE CAR3244 (
REGNO VARCHAR(20),
MODEL VARCHAR(30),
YEAR INT,
PRIMARY KEY(REGNO)
);

commit;

CREATE TABLE ACCIDENT3244 (
REPORT_NUMBER INT,
ACCD_DATE DATE,
LOCATION VARCHAR(50)
PRIMARY KEY(REPORT_NUMBER);
);

commit;

CREATE TABLE OWNS3244 (
DRIVER_ID VARCHAR(30),
REGNO VARCHAR(20),
FOREIGN KEY (DRIVER_ID) REFERENCES PERSON3244(DRIVER_ID),
FOREIGN KEY (REGNO) REFERENCES CAR3244(REGNO),
);

commit;

CREATE TABLE PARTICIPATED (
DRIVER_ID VARCHAR(30),
REGNO VARCHAR(20),
REPORT_NUMBER INT,
DAMAGE_AMOUNT INT
);

commit;