ALTER TABLE PARTICIPATED3244
ADD CONSTRAINT NEW_CONSTRAINT_1
FOREIGN KEY (REPORT_NUMBER)
REFERENCES ACCIDENT3244 (REPORT_NUMBER)
ON DELETE CASCADE;

DELETE FROM ACCIDENT3244
WHERE EXTRACT(YEAR FROM ACCD_DATE)=2017;

commit;