CREATE TABLE STUDENT3244 (
REGNO VARCHAR(20),
NAME VARCHAR(50),
MAJOR VARCHAR(20),
BDATE DATE,
PRIMARY KEY (REGNO)
);

CREATE TABLE COURSE3244 (
COURSEID INT,
CNAME VARCHAR(30),
DEPT VARCHAR(30),
PRIMARY KEY (COURSEID)
);

CREATE TABLE TEXT3244 (
BOOK_ISBN INT,
BOOKTITLE VARCHAR(50),
PUBLISHER VARCHAR(50),
AUTHOR VARCHAR(50)
);

CREATE TABLE BOOK_ADOPTION3244 (
COURSEID INT,
SEM INT,
BOOK_ISBN INT,
FOREIGN KEY (COURSEID) REFERENCES COURSE3244(COURSEID),
PRIMARY KEY (COURSEID)
);

CREATE TABLE ENROLL3244 (
REGNO VARCHAR(20),
COURSEID INT,
SEM INT,
BOOK_ISBN INT,
FOREIGN KEY (REGNO) REFERENCES STUDENT3244(REGNO),
FOREIGN KEY (COURSEID) REFERENCES COURSE3244(COURSEID),
PRIMARY KEY (REGNO, COURSEID)
);

COMMIT;